# Generated by Django 4.0.3 on 2022-03-12 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Livros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('autoria', models.CharField(max_length=100)),
                ('publicacao', models.IntegerField()),
                ('tipo', models.CharField(max_length=50)),
            ],
        ),
    ]
