# Generated by Django 4.0.3 on 2022-03-12 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jogos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('desenvolvedora', models.CharField(max_length=100)),
                ('distribuidora', models.CharField(max_length=100)),
                ('genero', models.CharField(max_length=50)),
                ('plataformas', models.CharField(max_length=100)),
                ('publicacao', models.IntegerField()),
            ],
        ),
    ]
